"""
This is a boilerplate pipeline 'model_stoch'
generated using Kedro 0.17.6
"""

from kedro.pipeline import Pipeline, node
from purple_controller.commons.nodes import (extract_model_solution_dataframes, get_current_ev_data, get_current_pv_data, get_ev_charge_limits, get_ev_charge_limits_stoch, get_history_ev_data, get_history_pv_data, get_model_ev_data, get_model_ev_scenarios,
                                             get_model_pv_data, get_model_timestamps, plot_sys_timeseries_simple, plot_sys_timeseries_stochastic, predict_ev_data, predict_pv_data, scenarios_ev_data, solve_model, store_model_solution_dataframes, store_model_solution_tables, store_model_solution_tables_stoch)
from .nodes import construct_model_stoch


def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(func=get_model_timestamps,
                 inputs="params:timing",
                 outputs="model_timestamps",
                 name="get_model_timestamps_node",
                 ),
            node(func=get_current_pv_data,
                 inputs=["processed_pv_data", "model_timestamps"],
                 outputs="current_pv_data",
                 name="get_current_pv_data_node",
                 ),
            node(func=get_current_ev_data,
                 inputs=["processed_ev_data", "model_timestamps"],
                 outputs="current_ev_data",
                 name="get_current_ev_data_node",
                 ),
            node(func=get_history_pv_data,
                 inputs=["processed_pv_data", "model_timestamps"],
                 outputs="history_pv_data",
                 name="get_history_pv_data_node",
                 ),
            node(func=get_history_ev_data,
                 inputs=["processed_ev_data", "model_timestamps"],
                 outputs="history_ev_data",
                 name="get_history_ev_data_node",
                 ),
            node(func=predict_pv_data,
                 inputs=["history_pv_data", "params:timing"],
                 outputs="predicted_pv_data",
                 name="get_predicted_pv_data_node",
                 ),
            node(func=scenarios_ev_data,
                 inputs=["history_ev_data", "params:timing"],
                 outputs="scenarios_ev_data",
                 name="get_scenarios_ev_data_node",
                 ),
            node(func=get_model_pv_data,
                 inputs=["current_pv_data", "predicted_pv_data"],
                 outputs="model_pv_data",
                 name="get_model_pv_data_node",
                 ),
            node(func=get_model_ev_scenarios,
                 inputs=["current_ev_data", "scenarios_ev_data"],
                 outputs="model_ev_scenarios",
                 name="get_model_ev_scenarios_node",
                 ),
            node(func=construct_model_stoch,
                 inputs=["params:timing", "config_model",
                         "model_pv_data", "model_ev_scenarios"],
                 outputs="unsolved_stoch_model",
                 name="construct_stoch_model_node",
                 ),
            node(func=solve_model,
                 inputs=["unsolved_stoch_model", "params:solverparams"],
                 outputs="solved_stoch_model",
                 name="solve_stoch_model_node",
                 ),
            node(func=extract_model_solution_dataframes,
                 inputs="solved_stoch_model",
                 outputs="stoch_solution_dictionary",
                 name="extract_stoch_solution_node",
                 ),
            node(func=store_model_solution_dataframes,
                 inputs="stoch_solution_dictionary",
                 outputs="stoch_solution_results",
                 name="store_stoch_solution_dataframes_node",
                 ),
            node(func=store_model_solution_tables_stoch,
                 inputs="stoch_solution_dictionary",
                 outputs=["table_result0_stoch", "table_result1_stoch",
                          "table_result2_stoch", "table_result3_stoch"],
                 name="store_stoch_solution_tables_node",
                 ),
            node(func=plot_sys_timeseries_stochastic,
                 inputs=["stoch_solution_dictionary",
                         "model_pv_data", "model_ev_scenarios"],
                 outputs="stoch_solution_plot",
                 name="plot_stoch_solution_node",
                 ),
            node(func=get_ev_charge_limits_stoch,
                 inputs=["stoch_solution_dictionary",
                         "params:general", "config_model"],
                 outputs="ev_charge_limits",
                 name="get_ev_charge_limits_node",
                 ),

        ])
