
timing:
  M_DT: .25 #1
  M_LA: 24 # lookahead hours
  M_LB: 8 # lookback days
  M_ST: "2022-03-01 08:07:09.188679" #"2016-01-15 00:00:40.188679" # start timestamp

solverparams:
  gap_relative: .1
  gap_absolute: .1
  timelimit: 600

location:
  lat: 47.44969
  lon: 9.91852